package com.kodlamaio.rentAcar.bussines.abstracts;

import java.util.List;

import com.kodlamaio.rentAcar.bussines.request.addresses.CreateCorporateCustomerAddressRequet;
import com.kodlamaio.rentAcar.bussines.request.addresses.CreateIndividualCustomerAddressRequest;
import com.kodlamaio.rentAcar.bussines.request.addresses.DeleteCorporateCustomerAddressRequest;
import com.kodlamaio.rentAcar.bussines.request.addresses.DeleteIndividualCustomerAddressRequest;
import com.kodlamaio.rentAcar.bussines.request.addresses.UpdateCorporateCustomerBillingAddressRequest;
import com.kodlamaio.rentAcar.bussines.request.addresses.UpdateCorporateCustomerContactAddressRequest;
import com.kodlamaio.rentAcar.bussines.request.addresses.UpdateIndividualCustomerBillingAddressRequest;
import com.kodlamaio.rentAcar.bussines.request.addresses.UpdateIndividualCustomerContactAddressRequest;
import com.kodlamaio.rentAcar.bussines.response.address.GetAllAddressResponse;
import com.kodlamaio.rentAcar.bussines.response.address.GetByIdAddressResponse;
import com.kodlamaio.rentAcar.core.utilities.result.DataResult;
import com.kodlamaio.rentAcar.core.utilities.result.Result;

public interface AddressService {
	Result addIndividualCustomerAddress(CreateIndividualCustomerAddressRequest createIndividualCustomerAddressRequest);
	Result addCorporateCustomerAddress(CreateCorporateCustomerAddressRequet createCorparateCustomerAddressRequet);
	
	Result deleteIndividualCustomerAddress(DeleteIndividualCustomerAddressRequest deleteIndividualCustomerAddressRequest);
	Result deleteCorporateCustomerAddress(DeleteCorporateCustomerAddressRequest deleteCorporateCustomerAddressRequest);
	
	Result updateIndividualCustomerContactAddress(UpdateIndividualCustomerContactAddressRequest updateIndividualCustomerContactAddressRequest);
	Result updateIndividualCustomerBillingAddress(UpdateIndividualCustomerBillingAddressRequest updateIndividualCustomerBillingAddressRequest);
	
	Result updateCorporateCustomerContactAddress(UpdateCorporateCustomerContactAddressRequest updateCorporateCustomerContactAddressRequest);
	Result updateCorporateCustomerBillingAddress(UpdateCorporateCustomerBillingAddressRequest updateCorporateCustomerBillingAddressRequest);
	
	DataResult<List<GetAllAddressResponse>> getAll();
	DataResult<GetByIdAddressResponse> getById(int id);
}
